// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *RegisterRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Token             string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	HeartbeatInterval int64                  `protobuf:"varint,2,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatInterval() int64 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Status        *NodeStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type NodeStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActiveSessions int64                  `protobuf:"varint,1,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	TotalBytesIn   int64                  `protobuf:"varint,2,opt,name=total_bytes_in,json=totalBytesIn,proto3" json:"total_bytes_in,omitempty"`
	TotalBytesOut  int64                  `protobuf:"varint,3,opt,name=total_bytes_out,json=totalBytesOut,proto3" json:"total_bytes_out,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_api_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStatus) GetActiveSessions() int64 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *NodeStatus) GetTotalBytesIn() int64 {
	if x != nil {
		return x.TotalBytesIn
	}
	return 0
}

func (x *NodeStatus) GetTotalBytesOut() int64 {
	if x != nil {
		return x.TotalBytesOut
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigUpdated bool                   `protobuf:"varint,1,opt,name=config_updated,json=configUpdated,proto3" json:"config_updated,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Policies      []*PolicyUpdate        `protobuf:"bytes,3,rep,name=policies,proto3" json:"policies,omitempty"` // 新增：动态策略列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetConfigUpdated() bool {
	if x != nil {
		return x.ConfigUpdated
	}
	return false
}

func (x *HeartbeatResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *HeartbeatResponse) GetPolicies() []*PolicyUpdate {
	if x != nil {
		return x.Policies
	}
	return nil
}

type PolicyUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BandwidthMbps int64                  `protobuf:"varint,2,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"` // 限速 (0 表示不修改)
	QuotaMb       int64                  `protobuf:"varint,3,opt,name=quota_mb,json=quotaMb,proto3" json:"quota_mb,omitempty"`                   // 配额 (0 表示不修改)
	Revoke        bool                   `protobuf:"varint,4,opt,name=revoke,proto3" json:"revoke,omitempty"`                                    // 是否立即吊销该用户权限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyUpdate) Reset() {
	*x = PolicyUpdate{}
	mi := &file_api_proto_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyUpdate) ProtoMessage() {}

func (x *PolicyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyUpdate.ProtoReflect.Descriptor instead.
func (*PolicyUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{5}
}

func (x *PolicyUpdate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PolicyUpdate) GetBandwidthMbps() int64 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *PolicyUpdate) GetQuotaMb() int64 {
	if x != nil {
		return x.QuotaMb
	}
	return 0
}

func (x *PolicyUpdate) GetRevoke() bool {
	if x != nil {
		return x.Revoke
	}
	return false
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_api_proto_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{6}
}

func (x *GetConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetConfigRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigData    []byte                 `protobuf:"bytes,1,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_api_proto_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigResponse) GetConfigData() []byte {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

type ReportStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Sessions      []*SessionStats        `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatsRequest) Reset() {
	*x = ReportStatsRequest{}
	mi := &file_api_proto_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatsRequest) ProtoMessage() {}

func (x *ReportStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatsRequest.ProtoReflect.Descriptor instead.
func (*ReportStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{8}
}

func (x *ReportStatsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportStatsRequest) GetSessions() []*SessionStats {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	BytesSent     int64                  `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStats) Reset() {
	*x = SessionStats{}
	mi := &file_api_proto_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStats) ProtoMessage() {}

func (x *SessionStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStats.ProtoReflect.Descriptor instead.
func (*SessionStats) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{9}
}

func (x *SessionStats) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStats) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

type ReportStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatsResponse) Reset() {
	*x = ReportStatsResponse{}
	mi := &file_api_proto_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatsResponse) ProtoMessage() {}

func (x *ReportStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatsResponse.ProtoReflect.Descriptor instead.
func (*ReportStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{10}
}

func (x *ReportStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_control_proto protoreflect.FileDescriptor

const file_api_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/control.proto\x12\vnodepass.v2\"\xbc\x01\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12:\n" +
	"\x04tags\x18\x03 \x03(\v2&.nodepass.v2.RegisterRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12-\n" +
	"\x12heartbeat_interval\x18\x02 \x01(\x03R\x11heartbeatInterval\"r\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12/\n" +
	"\x06status\x18\x03 \x01(\v2\x17.nodepass.v2.NodeStatusR\x06status\"\x83\x01\n" +
	"\n" +
	"NodeStatus\x12'\n" +
	"\x0factive_sessions\x18\x01 \x01(\x03R\x0eactiveSessions\x12$\n" +
	"\x0etotal_bytes_in\x18\x02 \x01(\x03R\ftotalBytesIn\x12&\n" +
	"\x0ftotal_bytes_out\x18\x03 \x01(\x03R\rtotalBytesOut\"\x8b\x01\n" +
	"\x11HeartbeatResponse\x12%\n" +
	"\x0econfig_updated\x18\x01 \x01(\bR\rconfigUpdated\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x125\n" +
	"\bpolicies\x18\x03 \x03(\v2\x19.nodepass.v2.PolicyUpdateR\bpolicies\"\x81\x01\n" +
	"\fPolicyUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ebandwidth_mbps\x18\x02 \x01(\x03R\rbandwidthMbps\x12\x19\n" +
	"\bquota_mb\x18\x03 \x01(\x03R\aquotaMb\x12\x16\n" +
	"\x06revoke\x18\x04 \x01(\bR\x06revoke\"A\n" +
	"\x10GetConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"4\n" +
	"\x11GetConfigResponse\x12\x1f\n" +
	"\vconfig_data\x18\x01 \x01(\fR\n" +
	"configData\"d\n" +
	"\x12ReportStatsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x125\n" +
	"\bsessions\x18\x02 \x03(\v2\x19.nodepass.v2.SessionStatsR\bsessions\"L\n" +
	"\fSessionStats\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x03R\tbytesSent\"/\n" +
	"\x13ReportStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc1\x02\n" +
	"\fControlPlane\x12G\n" +
	"\bRegister\x12\x1c.nodepass.v2.RegisterRequest\x1a\x1d.nodepass.v2.RegisterResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.nodepass.v2.HeartbeatRequest\x1a\x1e.nodepass.v2.HeartbeatResponse\x12J\n" +
	"\tGetConfig\x12\x1d.nodepass.v2.GetConfigRequest\x1a\x1e.nodepass.v2.GetConfigResponse\x12P\n" +
	"\vReportStats\x12\x1f.nodepass.v2.ReportStatsRequest\x1a .nodepass.v2.ReportStatsResponseB%Z#github.com/nodeox/NodePro/api/protob\x06proto3"

var (
	file_api_proto_control_proto_rawDescOnce sync.Once
	file_api_proto_control_proto_rawDescData []byte
)

func file_api_proto_control_proto_rawDescGZIP() []byte {
	file_api_proto_control_proto_rawDescOnce.Do(func() {
		file_api_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_control_proto_rawDesc), len(file_api_proto_control_proto_rawDesc)))
	})
	return file_api_proto_control_proto_rawDescData
}

var file_api_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_control_proto_goTypes = []any{
	(*RegisterRequest)(nil),     // 0: nodepass.v2.RegisterRequest
	(*RegisterResponse)(nil),    // 1: nodepass.v2.RegisterResponse
	(*HeartbeatRequest)(nil),    // 2: nodepass.v2.HeartbeatRequest
	(*NodeStatus)(nil),          // 3: nodepass.v2.NodeStatus
	(*HeartbeatResponse)(nil),   // 4: nodepass.v2.HeartbeatResponse
	(*PolicyUpdate)(nil),        // 5: nodepass.v2.PolicyUpdate
	(*GetConfigRequest)(nil),    // 6: nodepass.v2.GetConfigRequest
	(*GetConfigResponse)(nil),   // 7: nodepass.v2.GetConfigResponse
	(*ReportStatsRequest)(nil),  // 8: nodepass.v2.ReportStatsRequest
	(*SessionStats)(nil),        // 9: nodepass.v2.SessionStats
	(*ReportStatsResponse)(nil), // 10: nodepass.v2.ReportStatsResponse
	nil,                         // 11: nodepass.v2.RegisterRequest.TagsEntry
}
var file_api_proto_control_proto_depIdxs = []int32{
	11, // 0: nodepass.v2.RegisterRequest.tags:type_name -> nodepass.v2.RegisterRequest.TagsEntry
	3,  // 1: nodepass.v2.HeartbeatRequest.status:type_name -> nodepass.v2.NodeStatus
	5,  // 2: nodepass.v2.HeartbeatResponse.policies:type_name -> nodepass.v2.PolicyUpdate
	9,  // 3: nodepass.v2.ReportStatsRequest.sessions:type_name -> nodepass.v2.SessionStats
	0,  // 4: nodepass.v2.ControlPlane.Register:input_type -> nodepass.v2.RegisterRequest
	2,  // 5: nodepass.v2.ControlPlane.Heartbeat:input_type -> nodepass.v2.HeartbeatRequest
	6,  // 6: nodepass.v2.ControlPlane.GetConfig:input_type -> nodepass.v2.GetConfigRequest
	8,  // 7: nodepass.v2.ControlPlane.ReportStats:input_type -> nodepass.v2.ReportStatsRequest
	1,  // 8: nodepass.v2.ControlPlane.Register:output_type -> nodepass.v2.RegisterResponse
	4,  // 9: nodepass.v2.ControlPlane.Heartbeat:output_type -> nodepass.v2.HeartbeatResponse
	7,  // 10: nodepass.v2.ControlPlane.GetConfig:output_type -> nodepass.v2.GetConfigResponse
	10, // 11: nodepass.v2.ControlPlane.ReportStats:output_type -> nodepass.v2.ReportStatsResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_control_proto_init() }
func file_api_proto_control_proto_init() {
	if File_api_proto_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_control_proto_rawDesc), len(file_api_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_control_proto_goTypes,
		DependencyIndexes: file_api_proto_control_proto_depIdxs,
		MessageInfos:      file_api_proto_control_proto_msgTypes,
	}.Build()
	File_api_proto_control_proto = out.File
	file_api_proto_control_proto_goTypes = nil
	file_api_proto_control_proto_depIdxs = nil
}
